Cora:
  cl_lr: 0.0005
  num_hidden: 128
  num_proj_hidden: 128
  drop_edge_rate_1: 0.2
  drop_edge_rate_2: 0.4
  drop_feat_rate_1: 0.3
  drop_feat_rate_2: 0.4
  tau: 0.1
  cl_num_epochs: 200
  weight_decay: 0.00001
Pubmed:
  drop_edge_rate_1: 0.4
  drop_edge_rate_2: 0.1
  drop_feat_rate_1: 0.0
  drop_feat_rate_2: 0.2
  tau: 0.7
  cl_lr: 0.001
  weight_decay: 0.00001
  cl_num_epochs: 1500
  num_hidden: 256
  num_proj_hidden: 128
Computers:
    drop_edge_rate_1: 0.6
    drop_edge_rate_2: 0.3
    drop_feat_rate_1: 0.2
    drop_feat_rate_2: 0.3
    tau: 0.2
    cl_lr: 0.01
    weight_decay: 0.00001
    cl_num_epochs: 2000
    num_hidden: 128
    num_proj_hidden: 128
ogbn-arxiv:
    drop_edge_rate_1: 0.2
    drop_edge_rate_2: 0.3
    drop_feat_rate_1: 0.0
    drop_feat_rate_2: 0.0
    tau: 0.2
    cl_lr: 0.0005
    weight_decay: 0.00001
    cl_num_epochs: 400
    num_hidden: 512
    num_proj_hidden: 256
Photo:
    drop_edge_rate_1: 0.3
    drop_edge_rate_2: 0.5
    drop_feat_rate_1: 0.1
    drop_feat_rate_2: 0.1
    tau: 0.3
    cl_lr: 0.1
    weight_decay: 0.00001
    cl_num_epochs: 2000
    num_hidden: 256
    num_proj_hidden: 64
CS:
    drop_edge_rate_1: 0.3
    drop_edge_rate_2: 0.2
    drop_feat_rate_1: 0.3
    drop_feat_rate_2: 0.4
    tau: 0.4
    cl_lr: 0.1
    weight_decay: 0.00001
    cl_num_epochs: 1000
    num_hidden: 256
    num_proj_hidden: 256
Physics:
    drop_edge_rate_1: 0.4
    drop_edge_rate_2: 0.1
    drop_feat_rate_1: 0.1
    drop_feat_rate_2: 0.4
    tau: 0.5
    cl_lr: 0.01
    weight_decay: 0.00001
    cl_num_epochs: 1000
    num_hidden: 128
    num_proj_hidden: 64
WikiCS:
    drop_edge_rate_1: 0.5
    drop_edge_rate_2: 0.5
    drop_feat_rate_1: 0.1
    drop_feat_rate_2: 0.1
    tau: 0.1
    cl_lr: 0.01
    weight_decay: 0.00001
    cl_num_epochs: 1000
    num_hidden: 128
    num_proj_hidden: 128