MUTAG:
  cl_lr: 0.0005
  num_hidden: 128
  num_proj_hidden: 128
  drop_edge_rate_1: 0.3
  drop_edge_rate_2: 0.2
  drop_feat_rate_1: 0.2
  drop_feat_rate_2: 0.3
  drop_node_rate_1: 0.
  drop_node_rate_2: 0.1
  tau: 0.4
  cl_num_epochs: 400
  weight_decay: 0.00001
PROTEINS:
  drop_edge_rate_1: 0.3
  drop_edge_rate_2: 0.2
  drop_feat_rate_1: 0.2
  drop_feat_rate_2: 0.3
  drop_node_rate_1: 0.
  drop_node_rate_2: 0.
  tau: 0.7
  cl_lr: 0.001
  weight_decay: 0.00001
  cl_num_epochs: 200
  num_hidden: 256
  num_proj_hidden: 256

MNIST:
  drop_edge_rate_1: 0.4
  drop_edge_rate_2: 0.2
  drop_feat_rate_1: 0.3
  drop_feat_rate_2: 0.4
  drop_node_rate_1: 0.1
  drop_node_rate_2: 0.1
  tau: 0.7
  cl_lr: 0.001
  weight_decay: 0.00001
  cl_num_epochs: 600
  num_hidden: 256
  num_proj_hidden: 256

BBBP:
  drop_edge_rate_1: 0.4
  drop_edge_rate_2: 0.2
  drop_feat_rate_1: 0.3
  drop_feat_rate_2: 0.4
  drop_node_rate_1: 0.
  drop_node_rate_2: 0.
  tau: 0.7
  cl_lr: 0.001
  weight_decay: 0.00001
  cl_num_epochs: 400
  num_hidden: 256
  num_proj_hidden: 256


ogbg-ppa:
  drop_edge_rate_1: 0.3
  drop_edge_rate_2: 0.2
  drop_feat_rate_1: 0.2
  drop_feat_rate_2: 0.3
  drop_node_rate_1: 0.
  drop_node_rate_2: 0.1
  tau: 0.7
  cl_lr: 0.001
  weight_decay: 0.00001
  cl_num_epochs: 200
  num_hidden: 256
  num_proj_hidden: 256

ogbg-molhiv:
  drop_edge_rate_1: 0.3
  drop_edge_rate_2: 0.2
  drop_feat_rate_1: 0.2
  drop_feat_rate_2: 0.3
  drop_node_rate_1: 0.
  drop_node_rate_2: 0.1
  tau: 0.7
  cl_lr: 0.01
  weight_decay: 0.00001
  cl_num_epochs: 100
  num_hidden: 32
  num_proj_hidden: 32
